twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        version: '%app.version%'
        api_app: '%api_app%'
        metabase: '%metabase_root%'
        show_warning: '%app.warning%'
