vich_uploader:
    db_driver: orm

    mappings:
        documents:
            uri_prefix: /images/documents
            upload_destination: '%kernel.project_dir%/public/images/document'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
