vich_uploader:
    db_driver: orm

    mappings:
        documents:
            uri_prefix: /documents/navpro
            upload_destination: '%kernel.project_dir%/../documents/navpro/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false