# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'fr'
    app.version: '%env(resolve:APP_VERSION)%'
    api_navire: '%env(resolve:API_NAVIRE)%'
    api_natinf: '%env(resolve:API_NATINF)%'
    metabase_url: '%env(resolve:METABASE)%'
    metabase_key: '%env(resolve:METABASE_KEY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\NatinfFiller:
        arguments:
            $api: '%api_natinf%'

    # Explicit wiring for forms with event listeners
    App\Form\ControleNavireType:
        arguments: ['@App\Form\EventListener\ResetNatinfDataListener']

    App\Form\ControleEtablissementType:
        arguments: ['@App\Form\EventListener\ResetNatinfDataListener']

    App\Form\ControlePecheurPiedType:
        arguments: ['@App\Form\EventListener\ResetNatinfDataListener']


    # SonataAdminBundle related services
    admin.navire:
        class: App\Admin\NavireAdmin
        arguments: [~, App\Entity\Navire, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: rapport, label: "Navires" }
    admin.rapport:
        class: App\Admin\RapportAdmin
        arguments: [~, App\Entity\Rapport, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: rapport, label: "Rapports" }
    admin.etablissement:
        class: App\Admin\EtablissementAdmin
        arguments: [~, App\Entity\Etablissement, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: rapport, label: "Établissements" }
    admin.moyen:
        class: App\Admin\MoyenAdmin
        arguments: [~, App\Entity\Moyen, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: services, label: "Moyens par unité" }
    admin.zone_geographique:
        class: App\Admin\ZoneGeographiqueAdmin
        arguments: [~, App\Entity\ZoneGeographique, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: services, label: "Zones Géographiques" }
    admin.agent:
        class: App\Admin\AgentAdmin
        arguments: [~, App\Entity\Agent, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: services, label: Agent }

    admin.moyen_type_navire:
        class: App\Admin\MoyenTypeNavireAdmin
        arguments: [~, App\Entity\MoyenTypeNavire, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: "Type de navire" }
        public: true
